### ISSUE TITLE
Compilation broken after last git tag update

### ISSUE THREAD

**Issue by vrx-** [GEOS-ESM/GEOS-S2S-3#12]
I'm getting the following error with the latest git pull when building in Milan:

```
FAILED Waiting /gpfsm/dnb06/projects/p194/vruizxom/GEOS-S2S-3/Config/ESMA_post.mk:39: /gpfsm/dnb06/projects/p194/vruizxom/GEOS-S2S-3/Config/ESMA_post.mk:35: No (4 files in 3 packages)
Failed to compile 3/119 packages, 97.48% okay.
./gmh.pl -A /gpfsm/dnb06/projects/p194/vruizxom/GEOS-S2S-3/src/BUILD_LOG_DIR/LOG
else
exit 2
```

**Comment by mathomp4** [comment]
Huh. I'll try and take a look tomorrow. 

I should probably also bite the bullet and figure out if I can do CI for this. The Baselibs are from *waaaay* before we started any CI, so I don't have any Docker images for it. Hmmm.
